create table author
(
    id         int generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255)

);

create table member
(
    id         int generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255),
    status     varchar(255) check (status in ('ACTIVE', 'DEACTIVATED'))

);
create table book
(
    id        int generated by default as identity primary key,
    image_url varchar(255),
    isbn      varchar(255),
    name      varchar(255),
    author_id int,
    foreign key (author_id) references author (id)

);



create table lend
(
    id        int generated by default as identity primary key,
    status    smallint check (status between 0 and 1),
    due_on    timestamp(6) with time zone,
    start_on  timestamp(6) with time zone,
    member_id int,
    book_id   int,
    foreign key (member_id) references member (id),
    foreign key (status) references book (id)

);

